# create note entity
# @name CreateNote
POST http://localhost:8080/note
Content-Type: application/json

{
  "title": "Note - {{$guid}}",
  "content": "The content - {{$guid}}"
}

###

@TEMP_noteId = {{CreateNote.response.body.$.id}}

# get note by id
# @name GetNoteById
GET http://localhost:8080/note?noteId={{TEMP_noteId}}

###

# get all notes
# @name GetNotes
GET http://localhost:8080/notes