services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=notes_password #these are hardcoded for the purpose of testing
      - POSTGRES_DB=notes_database 
  notesapi:
    build:
      context: ./web-api
      dockerfile: Dockerfile
    depends_on:
      - postgres
    restart: on-failure
  